name: "Report a bug"
description: "File a bug report."
title: "[Bug]: "
type: "bug"
labels: bug
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: "This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our forum at https://forum.scylladb.com/ or in our slack channel https://slack.scylladb.com/ "
      options:
        - label: I have read the disclaimer above and am reporting a suspected malfunction in Scylla.
          required: true

  - type: input
    id: product-version
    attributes:
      label: product version
      description: Scylla version (or git commit hash)
      placeholder: ex. scylla-6.1.1
    validations:
      required: true
      
  - type: input
    id: cluster-size
    attributes:
      label: Cluster Size
    validations:
      required: true  
      
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: RHEL/CentOS/Ubuntu/AWS AMI
    validations:
      required: true
      
  - type: textarea
    id: additional-data
    attributes:
      label: Additional Environmental Data
      #description: 
      placeholder: Add additional data
      value: "Platform (physical/VM/cloud instance type/docker):\n
Hardware: sockets=   cores=   hyperthreading=   memory=\n
Disks: (SSD/HDD, count)"
    validations:
      required: false
      
  - type: textarea
    id: reproducer-steps
    attributes:
      label: Reproduction Steps
      placeholder: Describe how to reproduce the problem
      value: "The steps to reproduce the problem are:"
    validations:
      required: true
      
  - type: textarea
    id: the-problem
    attributes:
      label: What is the problem?
      placeholder: Describe the problem you found
      value: "The problem is that"
    validations:
      required: true
      
  - type: textarea
    id: what-happened
    attributes:
      label: Expected behavior?
      placeholder: Describe what should have happened
      value: "I expected that "
    validations:
      required: true
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
