#!/usr/bin/env python3
# Use the run.py library from ../cqlpy:
import sys
sys.path.insert(1, sys.path[0] + '/../cqlpy')
import run

import os
import requests
import signal

# When tests are to be run against AWS (the "--aws" option), it is not
# necessary to start Scylla at all. All we need to do is to run pytest.
if '--aws' in sys.argv:
    success = run.run_pytest(sys.path[0], ['-o', 'xfail_strict=false'] + sys.argv[1:])
    exit(0 if success else 1)

# check_alternator() below uses verify=False to accept self-signed SSL
# certificates but then we get scary warnings. This trick disables them:
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


# If the first option is "--release", download that release (see
# fetch_scylla.py for supported release numbers), and use that.
# The downloaded Scylla will be cached in the directory build/<release>,
# where <release> is the specific release downloaded - E.g., if the user
# asks "--release 2022.1" and the downloaded release is 2022.1.9, it
# will be stored in build/2022.1.9.
if len(sys.argv) > 1 and sys.argv[1] == '--release':
    release = sys.argv[2]
    exe = run.download_precompiled_scylla(release)
    run_scylla_cmd = lambda pid, dir: run.run_precompiled_scylla_cmd(exe, pid, dir)
    sys.argv = sys.argv[0:1] + sys.argv[3:]
    os.environ['SCYLLA'] = exe # so find_scylla() prints the right one
else:
    run_scylla_cmd = run.run_scylla_cmd

print('Scylla is: ' + run.find_scylla() + '.')

extra_scylla_options = []
remove_scylla_options = []

# If the "--vnodes" option is given, drop the "tablets" experimental
# feature (turned on in run.py) so that all tests will be run with the
# old vnode-based replication instead of tablets. This option only has
# temporary usefulness, and should eventually be removed.
if '--vnodes' in sys.argv:
    sys.argv.remove('--vnodes')
    remove_scylla_options.append('--enable-tablets=true')
    # Tablets are now enabled by default on some releases, it is not enough to remove the enable above.
    extra_scylla_options.append('--enable-tablets=false')
# test/alternator/run --interactive will not run any test. It will instead
# leave the server running and allow the user to connect to it. This server
# will be more practical to use if we do NOT enforce authorization.
if '--interactive' in sys.argv:
    remove_scylla_options.append('--alternator-enforce-authorization=1')

if "-h" in sys.argv or "--help" in sys.argv:
    run.run_pytest(sys.path[0], sys.argv)
    exit(0)

# run_alternator_cmd runs the same as run_scylla_cmd with *additional*
# parameters, so in particular both CQL and Alternator will be enabled.
# This is useful for us because we need CQL to setup authentication.
def run_alternator_cmd(pid, dir):
    (cmd, env) = run_scylla_cmd(pid, dir)
    ip = run.pid_to_ip(pid)
    cmd += [
        '--alternator-address', ip,
        '--alternator-enforce-authorization=1',
        '--alternator-write-isolation', 'only_rmw_uses_lwt',
        '--alternator-streams-time-window-s', '0',
        '--alternator-timeout-in-ms', '30000',
        # no longer needed here because it's defined in test/cqlpy/run.py
        # now that this parameter is used also by CQL's per-row TTL.
        #'--alternator-ttl-period-in-seconds', '0.5',
        '--alternator-allow-system-table-write=1',
        # this is required by test_streams.py test_parent_filtering and test_get_records_with_alternating_tablets_count
        # setting the value using scylla_config_temporary won't work, because the value is read
        # at the start and then periodically with `tablet-load-stats-refresh-interval-in-seconds`
        # interval, which by default is 60 seconds.
        '--tablet-load-stats-refresh-interval-in-seconds=1',
    ]
    if '--https' in sys.argv:
        run.setup_ssl_certificate(dir)
        cmd += ['--alternator-https-port', '8043',
            '--alternator-encryption-options', f'keyfile={dir}/scylla.key',
            '--alternator-encryption-options', f'certificate={dir}/scylla.crt',
        ]
    else:
        cmd += ['--alternator-port', '8000']
    if '--mtls' in sys.argv:
        if '--https' not in sys.argv:
            sys.exit('Error: --mtls requires --https')
        run.setup_mtls_certificate(dir)
        cmd += [
            '--alternator-encryption-options', 'require_client_auth=true',
            '--alternator-encryption-options', f'truststore={dir}/ca.crt',
        ]
    if '--vs' in sys.argv:
        cmd += run.vector_store_scylla_options(ip)
    cmd += extra_scylla_options

    for i in remove_scylla_options:
        cmd.remove(i)

    # Unfortunately, earlier Scylla versions required different command line
    # options to run, so for some old versions we need to drop some of the
    # command line options added above, or add more options. In cqlpy/run.py's
    # run_precompiled_scylla_cmd we already do this for most Scylla options,
    # but here we just need to take care of the Alternator-specific options
    # that we added here and were different in older versions.
    if 'release' in globals():
        version = release.split('~')[0].split('.')
        major = [int(version[0]), int(version[1])]
        if major < [2025,4]:
            cmd.remove('--alternator-allow-system-table-write=1')
        if major < [2026,3]:
            cmd.remove('--tablet-load-stats-refresh-interval-in-seconds=1')

    return (cmd, env)

pid = run.run_with_temporary_dir(run_alternator_cmd)
ip = run.pid_to_ip(pid)
scylla_dir = run.pid_to_dir(pid)

if '--https' in sys.argv:
    alternator_url=f"https://{ip}:8043"
else:
    alternator_url=f"http://{ip}:8000"

# If the "--vs" option is given, also run the vector store process (see
# run.run_vector_store() for where it looks for the vector store executable).
if '--vs' in sys.argv:
    sys.argv.remove('--vs')
    run.run_vector_store(ip)


# Wait for both CQL and Alternator APIs to become responsive. We obviously
# need the Alternator API to test Alternator, but currently we also need
# CQL for setting up authentication.
def check_alternator(url):
    try:
        cert = (f'{scylla_dir}/client.crt', f'{scylla_dir}/client.key') if '--mtls' in sys.argv else None
        requests.get(url, verify=False, cert=cert)
    except requests.ConnectionError:
        raise run.NotYetUp
    # Any other exception may indicate a problem, and is passed to the caller.

run.wait_for_services(pid, [
    lambda: run.check_cql(ip),
    lambda: check_alternator(alternator_url),
])

# test/alternator/run --interactive will not run any test. It will instead
# leave the server running and allow the user to interact with it. The user
# should interrupt this process (e.g., control-C) to kill the server.
if '--interactive' in sys.argv:
    if len(sys.argv) != 2:
        print('The "--interactive" option can be combined with "--release" or "--vs", but no other options.')
        exit(1)
    print(f'Scylla with Alternator is running without authorization enforced.\nConnect at: {alternator_url}\nPress Ctrl-C to stop.')
    signal.pause()

# Finally run pytest:
pytest_args = ['--url', alternator_url]
if '--mtls' in sys.argv:
    pytest_args += [f'--client-cert-file={scylla_dir}/client.crt',
                    f'--client-key-file={scylla_dir}/client.key']
success = run.run_pytest(sys.path[0],  pytest_args + sys.argv[1:])

run.summary = 'Alternator tests pass' if success else 'Alternator tests failure'

exit(0 if success else 1)

# Note that the run.cleanup_all() function runs now, just like on any exit
# for any reason in this script. It will delete the temporary files and
# announce the failure or success of the test (printing run.summary).
