/*
 * Copyright (C) 2026-present ScyllaDB
 */

/*
 * SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.1
 */

// Conformance test for Parquet Modular Encryption.
//
// The point of this file is that it does not test our writer against our reader. Round-tripping
// our own output proves the two halves agree with each other, which is exactly the failure mode
// that matters least: an encryption scheme is useful only if a *stock* Parquet reader with the
// right key can open the file, and only if we can open what a stock writer produced.
//
// So the fixtures are files written by parquet-cpp (through pyarrow 25.0.1), and this decrypts
// them with our own code: footer, page headers and page bodies, under both AES_GCM_V1 and
// AES_GCM_CTR_V1, with the footer key and with a separate column key. Every constant in
// encryption.cc -- module type numbers, the little-endian ordinal order, the length-nonce-
// ciphertext-tag envelope -- is pinned by these, not by our own assumptions.
//
// Fixtures: ~/pq-lab/data/enc_ref/*.parquet, generated by data/enc_ref/gen.py. The keys are the
// literals in that script; they are test keys and are meant to be in the source.

#include "encryption.hh"
#include "parquet_metadata.hh"

#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <span>
#include <string>
#include <vector>

using namespace sstables::parquet::format;

static int failures = 0;
static void check(bool ok, const std::string& what) {
    std::cout << (ok ? "  ok   " : "  FAIL ") << what << "\n";
    if (!ok) { ++failures; }
}

static std::vector<uint8_t> slurp(const std::string& p) {
    std::ifstream f(p, std::ios::binary);
    return std::vector<uint8_t>(std::istreambuf_iterator<char>(f),
                                std::istreambuf_iterator<char>());
}

// The reference files use pyarrow's "internal key material" mode: the data key is random and
// stored wrapped in the FileCryptoMetaData key_metadata JSON. gen.py's KMS wraps by base64, so
// the DEK is recoverable here without a KMS -- which is the point of using that mode for a
// fixture.
static std::vector<uint8_t> b64_decode(std::string_view s) {
    static const std::string tbl =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    std::vector<uint8_t> out;
    int val = 0, bits = -8;
    for (char c : s) {
        if (c == '=' || c == '\n' || c == '\r') { break; }
        auto pos = tbl.find(c);
        if (pos == std::string::npos) { continue; }
        val = (val << 6) + int(pos);
        bits += 6;
        if (bits >= 0) { out.push_back(uint8_t((val >> bits) & 0xff)); bits -= 8; }
    }
    return out;
}

static std::string json_string_field(const std::string& j, const std::string& key) {
    auto k = "\"" + key + "\"";
    auto p = j.find(k);
    if (p == std::string::npos) { return {}; }
    p = j.find(':', p + k.size());
    if (p == std::string::npos) { return {}; }
    auto a = j.find('"', p);
    if (a == std::string::npos) { return {}; }
    auto b = j.find('"', a + 1);
    return j.substr(a + 1, b - a - 1);
}

int main(int argc, char** argv) {
    const std::string dir = argc > 1 ? argv[1]
        : std::string(getenv("HOME") ? getenv("HOME") : ".") + "/pq-lab/data/enc_ref";
    if (!std::filesystem::exists(dir + "/uniform_gcm.parquet")) {
        std::cout << "reference files not found in " << dir
                  << " -- generate them with data/enc_ref/gen.py\n";
        return 2;
    }

    struct fixture { const char* name; cipher algo; };
    const fixture fixtures[] = {
        {"uniform_gcm", cipher::aes_gcm_v1},
        {"percol_gcm",  cipher::aes_gcm_v1},
        {"uniform_ctr", cipher::aes_gcm_ctr_v1},
    };

    for (const auto& fx : fixtures) {
        std::cout << "== " << fx.name << "\n";
        auto img = slurp(dir + "/" + fx.name + ".parquet");
        check(!img.empty(), "fixture read");
        check(has_encrypted_footer(img), "recognised as an encrypted-footer file (PARE)");
        check(std::memcmp(img.data(), magic_encrypted, 4) == 0, "leading magic is PARE");

        // Tail: [FileCryptoMetaData][encrypted FileMetaData][4-byte length][PARE]
        uint32_t region = uint32_t(img[img.size() - 8]) | (uint32_t(img[img.size() - 7]) << 8)
                        | (uint32_t(img[img.size() - 6]) << 16)
                        | (uint32_t(img[img.size() - 5]) << 24);
        check(region + 8 <= img.size(), "footer region length in range");
        std::span<const uint8_t> tail(img.data() + img.size() - 8 - region, region);

        size_t consumed = 0;
        auto fcm = parse_file_crypto_metadata(tail, &consumed);
        check(fcm.algo == fx.algo, "algorithm matches the fixture");
        check(fcm.aad_file_unique.size() == 8, "aad_file_unique is 8 bytes");
        check(!fcm.supply_aad_prefix, "supply_aad_prefix is false");
        check(fcm.key_metadata.has_value(), "key_metadata present");

        // Round-trip our own serialiser against the bytes parquet-cpp wrote. This is a stricter
        // check than "we can parse it": it says we would have written the same structure.
        {
            file_crypto_metadata mine = fcm;
            auto re = write_file_crypto_metadata(mine);
            check(re.size() == consumed
                  && std::memcmp(re.data(), tail.data(), re.size()) == 0,
                  "our FileCryptoMetaData serialisation is byte-identical");
        }

        auto dek = b64_decode(json_string_field(*fcm.key_metadata, "wrappedDEK"));
        check(dek.size() == 16, "unwrapped DEK is 16 bytes");
        encryption_key key{dek};

        // ---- footer (module 0, no ordinals)
        auto aad = build_aad(fcm.aad_prefix, fcm.aad_file_unique, module_type::footer);
        std::vector<uint8_t> footer;
        bool footer_ok = true;
        try {
            footer = decrypt_module(tail.subspan(consumed), key, aad, nullptr, fcm.algo, false);
        } catch (const std::exception& e) {
            footer_ok = false;
            std::cout << "         " << e.what() << "\n";
        }
        check(footer_ok && !footer.empty(), "footer decrypts");
        if (!footer_ok) { continue; }

        file_metadata md;
        bool parsed = true;
        try {
            md = parse_file_metadata(footer);
        } catch (const std::exception& e) {
            parsed = false;
            std::cout << "         " << e.what() << "\n";
        }
        check(parsed, "decrypted footer parses as FileMetaData");
        if (!parsed) { continue; }

        // With a per-column key, the footer must *say* so rather than merely omit the metadata.
        // This is the distinction the parser now makes, and it is what lets a reader report
        // "no key for column b" instead of "corrupt file".
        if (std::string(fx.name) == "percol_gcm") {
            const auto& chunks = md.row_groups[0].columns;
            check(chunks.size() == 2, "two chunks");
            check(chunks[0].meta.has_value() && !chunks[0].metadata_is_encrypted(),
                  "column a: metadata inline, footer key");
            check(!chunks[1].meta.has_value() && chunks[1].metadata_is_encrypted(),
                  "column b: metadata encrypted under its own key");
            check(chunks[1].crypto_metadata && !chunks[1].crypto_metadata->with_footer_key,
                  "column b: ColumnCryptoMetaData says column key");
            check(chunks[1].crypto_metadata
                      && chunks[1].crypto_metadata->path_in_schema == std::vector<std::string>{"b"},
                  "column b: crypto metadata names the column");

            // And with the column key, the encrypted ColumnMetaData decrypts and parses.
            bool col_ok = false;
            if (chunks[1].crypto_metadata && chunks[1].crypto_metadata->key_metadata
                && chunks[1].encrypted_column_metadata) {
                auto cdek = b64_decode(json_string_field(*chunks[1].crypto_metadata->key_metadata,
                                                         "wrappedDEK"));
                encryption_key ckey{cdek};
                auto cmaad = build_aad(fcm.aad_prefix, fcm.aad_file_unique,
                                       module_type::column_metadata, 0, 1);
                try {
                    auto blob = std::span<const uint8_t>(
                            reinterpret_cast<const uint8_t*>(chunks[1].encrypted_column_metadata->data()),
                            chunks[1].encrypted_column_metadata->size());
                    auto cm = decrypt_module(blob, ckey, cmaad, nullptr, fcm.algo, false);
                    col_ok = !cm.empty() && cm[0] == 0x15;
                } catch (const std::exception& e) {
                    std::cout << "         column metadata: " << e.what() << "\n";
                }
            }
            check(col_ok, "column b: encrypted ColumnMetaData decrypts with the column key");
        }
        check(md.num_rows == 100, "row count is 100");
        check(md.row_groups.size() == 1, "one row group");

        // ---- page headers (module 4) and page bodies (module 2), per column
        //
        // percol_gcm is the interesting case, and not the one you would guess: parquet-cpp
        // encrypts only the columns named in column_keys. Column 'a' is not named, so its pages
        // are *plaintext* inside an otherwise encrypted file and it carries no
        // ColumnCryptoMetaData at all. Partial encryption is legal, and a reader has to cope with
        // a file mixing encrypted and clear columns -- which is what an "encrypt the PII columns
        // only" deployment actually produces.
        const bool per_column = std::string(fx.name) == "percol_gcm";
        for (size_t c = 0; c < md.row_groups[0].columns.size(); ++c) {
            const auto& ch = md.row_groups[0].columns[c];
            const bool clear = per_column && c == 0;
            if (!ch.meta) {
                // Encrypted metadata: proved above that it opens with the column key, and the
                // page offsets live inside it, so there is nothing further to do without it.
                check(per_column && c == 1, "chunk without inline metadata is the column-key one");
                continue;
            }
            const auto off = size_t(ch.meta->data_page_offset);
            check(off < img.size(), "data page offset in range");
            if (clear) {
                check(!ch.crypto_metadata.has_value(),
                      "column a carries no ColumnCryptoMetaData (it is not encrypted)");
                // A plaintext page header starts with the thrift struct directly rather than a
                // 4-byte module length, and asserting that is what proves it is really in clear.
                check(img[off] == 0x15, "column a page header is plaintext thrift");
                bool refused = false;
                auto hdr_aad = build_aad(fcm.aad_prefix, fcm.aad_file_unique,
                                         module_type::data_page_header, 0, int(c), 0);
                try {
                    (void) decrypt_module(std::span<const uint8_t>(img).subspan(off), key,
                                          hdr_aad, nullptr, fcm.algo, false);
                } catch (const std::exception&) { refused = true; }
                check(refused, "and does not decrypt as an encrypted module");
                continue;
            }
            auto hdr_aad = build_aad(fcm.aad_prefix, fcm.aad_file_unique,
                                     module_type::data_page_header, 0, int(c), 0);
            size_t hdr_used = 0;
            std::vector<uint8_t> hdr;
            bool ok = true;
            try {
                hdr = decrypt_module(std::span<const uint8_t>(img).subspan(off), key, hdr_aad,
                                     &hdr_used, fcm.algo, false);
            } catch (const std::exception& e) {
                ok = false;
                std::cout << "         col " << c << " header: " << e.what() << "\n";
            }
            check(ok, std::string("column ") + std::to_string(c)
                      + " page header decrypts with the footer key");
            if (!ok) { continue; }
            check(!hdr.empty() && hdr[0] == 0x15,
                  std::string("column ") + std::to_string(c) + " page header is thrift");

            auto body_aad = build_aad(fcm.aad_prefix, fcm.aad_file_unique,
                                      module_type::data_page, 0, int(c), 0);
            bool body_ok = true;
            try {
                auto body = decrypt_module(std::span<const uint8_t>(img).subspan(off + hdr_used),
                                           key, body_aad, nullptr, fcm.algo,
                                           fcm.algo == cipher::aes_gcm_ctr_v1);
                body_ok = !body.empty();
            } catch (const std::exception& e) {
                body_ok = false;
                std::cout << "         body: " << e.what() << "\n";
            }
            check(body_ok, std::string("column ") + std::to_string(c) + " page body decrypts");
        }

        // ---- tamper detection: flip one ciphertext byte and the tag must reject it
        if (fx.algo == cipher::aes_gcm_v1) {
            auto bad = std::vector<uint8_t>(tail.begin(), tail.end());
            bad[consumed + 4 + nonce_len + 1] ^= 0x01;
            bool threw = false;
            try {
                (void) decrypt_module(std::span<const uint8_t>(bad).subspan(consumed), key, aad,
                                      nullptr, fcm.algo, false);
            } catch (const std::exception&) { threw = true; }
            check(threw, "a flipped ciphertext byte fails authentication");

            // And the AAD is load-bearing: the same ciphertext under a different module type
            // must not verify, which is what stops a module being relocated in the file.
            auto wrong = build_aad(fcm.aad_prefix, fcm.aad_file_unique,
                                   module_type::column_metadata);
            threw = false;
            try {
                (void) decrypt_module(tail.subspan(consumed), key, wrong, nullptr, fcm.algo, false);
            } catch (const std::exception&) { threw = true; }
            check(threw, "the wrong module type in the AAD fails authentication");
        }
    }

    std::cout << (failures ? "ENCRYPTION CONFORMANCE FAIL" : "ENCRYPTION CONFORMANCE PASS")
              << " (" << failures << " failures)\n";
    return failures ? 1 : 0;
}
