# This file was translated from the original Java test from the Apache
# Cassandra source repository, as of commit 4ab8bac4a51f8aef0d55b2497699e1291baeda4b
#
# The original Apache Cassandra license:
#
# SPDX-License-Identifier: Apache-2.0
#
# Modifications: Copyright 2026-present ScyllaDB
# SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.1

from .porting import *
from ..test_materialized_view_old import clock

# The original Java test class is parameterized to run each test with each of
# the CQL protocol versions which Cassandra supports. We use only the Python
# driver's default protocol version.

# Translation of ViewAbstractParameterizedTest.updateViewWithFlush(). The
# Java updateView() waits for asynchronous view updates; on a single node
# both Scylla and Cassandra apply them synchronously, so we just execute().
def updateViewWithFlush(cql, table, query, flush, *args):
    execute(cql, table, query, *args)
    if flush:
        nodetool.flush_keyspace(cql, table.split('.')[0])

# for now, unselected column cannot be fully supported, see CASSANDRA-11500
# (The Java test is marked @Ignore, because Cassandra fails it. Scylla
# supports unselected columns using "virtual columns" in the view.)
def testPartialDeleteUnselectedColumnWithFlush(cql, test_keyspace, cassandra_bug):
    partialDeleteUnselectedColumn(cql, test_keyspace, True)

# for now, unselected column cannot be fully supported, see CASSANDRA-11500
def testPartialDeleteUnselectedColumnWithoutFlush(cql, test_keyspace, cassandra_bug):
    partialDeleteUnselectedColumn(cql, test_keyspace, False)

def partialDeleteUnselectedColumn(cql, test_keyspace, flush):
    with create_table(cql, test_keyspace, "(k int, c int, a int, b int, PRIMARY KEY (k, c))") as table:
        with create_view(cql, table, "CREATE MATERIALIZED VIEW %s AS " +
                                     "SELECT k,c FROM %s WHERE k IS NOT NULL AND c IS NOT NULL PRIMARY KEY (k,c)") as view, \
             nodetool.no_autocompaction_context(cql, view):

            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 10 SET b=1 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, 1))
            assert_rows(execute(cql, view, "SELECT * FROM %s"), row(1, 1))
            updateViewWithFlush(cql, table, "DELETE b FROM %s USING TIMESTAMP 11 WHERE k=1 AND c=1", flush)
            assert_empty(execute(cql, table, "SELECT * from %s"))
            assert_empty(execute(cql, view, "SELECT * FROM %s"))
            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 1 SET a=1 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, 1, None))
            assert_rows(execute(cql, view, "SELECT * FROM %s"), row(1, 1))

            execute(cql, table, "truncate %s;")

            # removal generated by unselected column should not shadow PK update with smaller timestamp
            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 18 SET a=1 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, 1, None))
            assert_rows(execute(cql, view, "SELECT * FROM %s"), row(1, 1))

            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 20 SET a=null WHERE k=1 AND c=1", flush)
            assert_empty(execute(cql, table, "SELECT * from %s"))
            assert_empty(execute(cql, view, "SELECT * FROM %s"))

            updateViewWithFlush(cql, table, "INSERT INTO %s(k,c) VALUES(1,1) USING TIMESTAMP 15", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, None))
            assert_rows(execute(cql, view, "SELECT * FROM %s"), row(1, 1))

def testPartialDeleteSelectedColumnWithFlush(cql, test_keyspace, clock):
    partialDeleteSelectedColumn(cql, test_keyspace, clock, True)

def testPartialDeleteSelectedColumnWithoutFlush(cql, test_keyspace, clock):
    partialDeleteSelectedColumn(cql, test_keyspace, clock, False)

def partialDeleteSelectedColumn(cql, test_keyspace, clock, flush):
    with create_table(cql, test_keyspace, "(k int, c int, a int, b int, e int, f int, PRIMARY KEY (k, c))") as table:
        with create_view(cql, table, "CREATE MATERIALIZED VIEW %s AS SELECT a, b, c, k FROM %s " +
                                     "WHERE k IS NOT NULL AND c IS NOT NULL PRIMARY KEY (k,c)") as view, \
             nodetool.no_autocompaction_context(cql, view):

            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 10 SET b=1 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, 1, None, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, None, 1))

            updateViewWithFlush(cql, table, "DELETE b FROM %s USING TIMESTAMP 11 WHERE k=1 AND c=1", flush)
            assert_empty(execute(cql, table, "SELECT * from %s"))
            assert_empty(execute(cql, view, "SELECT * from %s"))

            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 1 SET a=1 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, 1, None, None, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, 1, None))

            updateViewWithFlush(cql, table, "DELETE a FROM %s USING TIMESTAMP 1 WHERE k=1 AND c=1", flush)
            assert_empty(execute(cql, table, "SELECT * from %s"))
            assert_empty(execute(cql, view, "SELECT * from %s"))

            # view livenessInfo should not be affected by selected column ts or tb
            updateViewWithFlush(cql, table, "INSERT INTO %s(k,c) VALUES(1,1) USING TIMESTAMP 0", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, None, None, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, None, None))

            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 12 SET b=1 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, 1, None, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, None, 1))

            updateViewWithFlush(cql, table, "DELETE b FROM %s USING TIMESTAMP 13 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, None, None, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, None, None))

            updateViewWithFlush(cql, table, "DELETE FROM %s USING TIMESTAMP 14 WHERE k=1 AND c=1", flush)
            assert_empty(execute(cql, table, "SELECT * from %s"))
            assert_empty(execute(cql, view, "SELECT * from %s"))

            updateViewWithFlush(cql, table, "INSERT INTO %s(k,c) VALUES(1,1) USING TIMESTAMP 15", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, None, None, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, None, None))

            updateViewWithFlush(cql, table, "UPDATE %s USING TTL 3 SET b=1 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, 1, None, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, None, 1))

            # The Java test sleeps 4 seconds here.
            clock.jump(4)

            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, None, None, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, None, None))

            updateViewWithFlush(cql, table, "DELETE FROM %s USING TIMESTAMP 15 WHERE k=1 AND c=1", flush)
            assert_empty(execute(cql, table, "SELECT * from %s"))
            assert_empty(execute(cql, view, "SELECT * from %s"))

            execute(cql, table, "truncate %s;")

            # removal generated by unselected column should not shadow selected column with smaller timestamp
            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 18 SET e=1 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, None, None, 1, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, None, None))

            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 18 SET e=null WHERE k=1 AND c=1", flush)
            assert_empty(execute(cql, table, "SELECT * from %s"))
            assert_empty(execute(cql, view, "SELECT * from %s"))

            updateViewWithFlush(cql, table, "UPDATE %s USING TIMESTAMP 16 SET a=1 WHERE k=1 AND c=1", flush)
            assert_rows(execute(cql, table, "SELECT * from %s"), row(1, 1, 1, None, None, None))
            assert_rows(execute(cql, view, "SELECT * from %s"), row(1, 1, 1, None))

def testRangeDeletionWithFlush(cql, test_keyspace):
    rangeDeletion(cql, test_keyspace, True)

def testRangeDeletionWithoutFlush(cql, test_keyspace):
    rangeDeletion(cql, test_keyspace, False)

def rangeDeletion(cql, test_keyspace, flush):
    # for partition range deletion, need to know that existing row is shadowed instead of not existed.
    with create_table(cql, test_keyspace, "(a int, b int, c int, d int, PRIMARY KEY (a))") as table:
        with create_view(cql, table, "CREATE MATERIALIZED VIEW %s AS SELECT * FROM %s " +
                                     "WHERE a IS NOT NULL AND b IS NOT NULL PRIMARY KEY (a, b)") as view, \
             nodetool.no_autocompaction_context(cql, view):

            updateViewWithFlush(cql, table, "INSERT INTO %s (a, b, c, d) VALUES (?, ?, ?, ?) using timestamp 0", flush, 1, 1, 1, 1)

            assert_rows_ignoring_order(execute(cql, view, "SELECT * FROM %s"), row(1, 1, 1, 1))

            # remove view row
            updateViewWithFlush(cql, table, "UPDATE %s using timestamp 1 set b = null WHERE a=1", flush)

            assert_empty(execute(cql, view, "SELECT * FROM %s"))
            # remove base row, no view updated generated.
            updateViewWithFlush(cql, table, "DELETE FROM %s using timestamp 2 where a=1", flush)

            assert_empty(execute(cql, view, "SELECT * FROM %s"))

            # restor view row with b,c column. d is still tombstone
            updateViewWithFlush(cql, table, "UPDATE %s using timestamp 3 set b = 1,c = 1 where a=1", flush) # upsert

            assert_rows_ignoring_order(execute(cql, view, "SELECT * FROM %s"), row(1, 1, 1, None))
