#!/bin/sh

if [ $# -eq 0 ]; then
    echo "usage: $0 version"
    exit 1
fi

version=$1

sed -i -e "s/^VERSION.*/VERSION=$version/g" SCYLLA-VERSION-GEN
git commit -m "release: prepare for $version" SCYLLA-VERSION-GEN
