#!/usr/bin/env python3
# Use the run.py library from ../cqlpy:
import sys
sys.path.insert(1, sys.path[0] + '/../cqlpy')
import run

success = run.run_pytest(sys.path[0], sys.argv[1:])

run.summary = 'Pylib tests pass' if success else 'Pylib tests failure'

exit(0 if success else 1)
