/*
 * Copyright (C) 2026-present ScyllaDB
 */

/*
 * SPDX-License-Identifier: (LicenseRef-ScyllaDB-Source-Available-1.1 and Apache-2.0)
 */

#pragma once

#include <cstdint>
#include <string_view>
#include <unordered_map>

namespace aws {

class aws_error;
using aws_errors = std::unordered_map<std::string_view, const aws_error>;

enum class aws_error_type : uint8_t {
    INCOMPLETE_SIGNATURE = 0,
    INTERNAL_FAILURE = 1,
    INVALID_ACTION = 2,
    INVALID_CLIENT_TOKEN_ID = 3,
    INVALID_PARAMETER_COMBINATION = 4,
    INVALID_QUERY_PARAMETER = 5,
    INVALID_PARAMETER_VALUE = 6,
    MISSING_ACTION = 7,
    MISSING_AUTHENTICATION_TOKEN = 8,
    MISSING_PARAMETER = 9,
    OPT_IN_REQUIRED = 10,
    REQUEST_EXPIRED = 11,
    SERVICE_UNAVAILABLE = 12,
    THROTTLING = 13,
    VALIDATION = 14,
    ACCESS_DENIED = 15,
    RESOURCE_NOT_FOUND = 16,
    UNRECOGNIZED_CLIENT = 17,
    MALFORMED_QUERY_STRING = 18,
    SLOW_DOWN = 19,
    REQUEST_TIME_TOO_SKEWED = 20,
    INVALID_SIGNATURE = 21,
    SIGNATURE_DOES_NOT_MATCH = 22,
    INVALID_ACCESS_KEY_ID = 23,
    REQUEST_TIMEOUT = 24,
    NOT_INITIALIZED = 25,
    MEMORY_ALLOCATION = 26,
    NETWORK_CONNECTION = 99,
    UNKNOWN = 100,
    CLIENT_SIGNING_FAILURE = 101,
    USER_CANCELLED = 102,
    ENDPOINT_RESOLUTION_FAILURE = 103,
    // HTTP errors without additional information in the response body
    HTTP_NOT_IMPLEMENTED = 114,
    HTTP_UNAUTHORIZED = 115,
    HTTP_FORBIDDEN = 116,
    HTTP_NOT_FOUND = 117,
    HTTP_TOO_MANY_REQUESTS = 118,
    HTTP_INTERNAL_SERVER_ERROR = 119,
    HTTP_BANDWIDTH_LIMIT_EXCEEDED = 120,
    HTTP_SERVICE_UNAVAILABLE = 121,
    HTTP_REQUEST_TIMEOUT = 122,
    HTTP_PAGE_EXPIRED = 123,
    HTTP_LOGIN_TIMEOUT = 124,
    HTTP_GATEWAY_TIMEOUT = 125,
    HTTP_NETWORK_CONNECT_TIMEOUT = 126,
    HTTP_NETWORK_READ_TIMEOUT = 127,
    SERVICE_EXTENSION_START_RANGE = 128,
    // Service-specific error values below are generated from the AWS c2j
    // models by scripts/gen_aws_service_errors.py. Do not edit by hand.
    // @SCYLLA_AWS_ERRORS_BEGIN@
    // S3
    ANNOTATION_LIMIT_EXCEEDED,
    ANNOTATION_NAME_TOO_LONG,
    BUCKET_ALREADY_EXISTS,
    BUCKET_ALREADY_OWNED_BY_YOU,
    ENCRYPTION_TYPE_MISMATCH,
    IDEMPOTENCY_PARAMETER_MISMATCH,
    INVALID_ANNOTATION_NAME,
    INVALID_OBJECT_STATE,
    INVALID_PREFIX,
    INVALID_REQUEST,
    INVALID_WRITE_OFFSET,
    NO_SUCH_ANNOTATION,
    NO_SUCH_BUCKET,
    NO_SUCH_KEY,
    NO_SUCH_UPLOAD,
    OBJECT_ALREADY_IN_ACTIVE_TIER,
    OBJECT_NOT_IN_ACTIVE_TIER,
    TOO_MANY_PARTS,
    UNSUPPORTED_MEDIA_TYPE,
    // STS
    EXPIRED_TOKEN,
    EXPIRED_TRADE_IN_TOKEN,
    INVALID_AUTHORIZATION_MESSAGE,
    INVALID_IDENTITY_TOKEN,
    I_D_P_COMMUNICATION_ERROR,
    I_D_P_REJECTED_CLAIM,
    J_W_T_PAYLOAD_SIZE_EXCEEDED,
    MALFORMED_POLICY_DOCUMENT,
    OUTBOUND_WEB_IDENTITY_FEDERATION_DISABLED,
    PACKED_POLICY_TOO_LARGE,
    REGION_DISABLED,
    SESSION_DURATION_ESCALATION,
    // @SCYLLA_AWS_ERRORS_END@
    // No error set
    OK = 255
};

} // namespace aws
